# Generated by Django 4.0.5 on 2022-06-09 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remote_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('calling_number', models.PositiveSmallIntegerField(unique_for_date='date')),
                ('status', models.CharField(choices=[('D', 'Delivered'), ('P', 'Preparing'), ('R', 'Ready'), ('C', 'Received')], default='C', max_length=2)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.table')),
            ],
        ),
    ]
